version: 2
updates:
  - package-ecosystem: gomod
    directory: "/"
    allow:
      # Allow both direct and indirect updates for all packages
      - dependency-type: "all"
    schedule:
      interval: "monthly"
    reviewers:
      - "rtuk"
      - "Lveltmaat"
      - "TheM1984"


