# Example probe config file for the Script Exporter

probes:
  - name: example1
    cmd: /usr/local/bin/python3
    labels:
      - key: foo
        value: bar
      - key: baz
        value: qux
    arguments:
      - default: ./test/resources/ok_print_arguments.py
      - dynamic: true
        param: first
        default: hello
      - dynamic: true
        type: dynamic
        param: second
  - name: example2
    cmd: /usr/local/bin/python3
    arguments:
      - default: ./test/resources/error_print_arguments.py
      - dynamic: true
        param: foo
        default: hello
      - dynamic: true
        type: dynamic
        param: bar
