name: build tar files and publish to releases

on:
  push:
    branches: [ master ]

jobs:
  build:
    name: Build tar files and release to releases
    runs-on: ubuntu-latest

    steps:
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: checkout repo
      uses: actions/checkout@v2

    - name: read version file
      id: getversion
      run: echo "::set-output name=version::$(cat VERSION)"

    - name: Build tar files
      run: make dist

    - name: create the release
      id: create-new-release
      uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        prerelease: false
        automatic_release_tag: ${{ steps.getversion.outputs.version }}+${{ github.run_number }}
        title: ${{ steps.getversion.outputs.version }}+${{ github.run_number }}

    - name: upload release assets windows
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create-new-release.outputs.upload_url }}
        asset_path: ./dist/script_exporter-${{ steps.getversion.outputs.version }}-windows-amd64.tar.gz
        asset_name: script_exporter-${{ steps.getversion.outputs.version }}-windows-amd64.tar.gz
        asset_content_type: application/zip

    - name: upload release assets linux
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create-new-release.outputs.upload_url }}
        asset_path: ./dist/script_exporter-${{ steps.getversion.outputs.version }}-linux-amd64.tar.gz
        asset_name: script_exporter-${{ steps.getversion.outputs.version }}-linux-amd64.tar.gz
        asset_content_type: application/zip

    - name: upload release assets darwin
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create-new-release.outputs.upload_url }}
        asset_path: ./dist/script_exporter-${{ steps.getversion.outputs.version }}-darwin-amd64.tar.gz
        asset_name: script_exporter-${{ steps.getversion.outputs.version }}-darwin-amd64.tar.gz
        asset_content_type: application/zip

    - name: upload release assets freebsd
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create-new-release.outputs.upload_url }}
        asset_path: ./dist/script_exporter-${{ steps.getversion.outputs.version }}-freebsd-amd64.tar.gz
        asset_name: script_exporter-${{ steps.getversion.outputs.version }}-freebsd-amd64.tar.gz
        asset_content_type: application/zip
