name: build tar files and publish to releases

on:
  push:
    branches: [ master ]

jobs:
  build:
    name: Build tar files and release to releases
    runs-on: ubuntu-latest

    steps:
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: 'stable'

    - name: checkout repo
      uses: actions/checkout@v4

    - name: read version file
      id: getversion
      run: echo "version=$(make version)" >> $GITHUB_OUTPUT

    - name: Install UPX
      run: sudo apt-get update && sudo apt-get install -y upx

    - name: Build tar files
      run: make dist

    - name: create the release
      uses: softprops/action-gh-release@v1
      with:
        prerelease: false
        tag_name: ${{ steps.getversion.outputs.version }}+${{ github.run_number }}
        files: ./dist/*.tar.gz
        fail_on_unmatched_files: true
